### ISSUE TITLE
请问那个./weights/openpose.jit这个文件在哪里？

### ISSUE THREAD

**Issue by 948024326** [zhuoxiangpang/ism_person_openpose#1]

**Comment by zhuoxiangpang** [comment]
@948024326 感谢您点进来这个项目。
这个项目里面有yolov5及lightweightopenpose，它们相关的权重文件及.jit文件在这个百度云盘里面。
地址:https://pan.baidu.com/s/1rzI9XO5qCs25LaIbcKybRw    密码:pmwj

**Comment by 948024326** [comment]
谢谢了哈
