### ISSUE TITLE
在检测视频的时候如何将结果显示出来

### ISSUE THREAD

**Issue by 1180610212** [zhuoxiangpang/ism_person_openpose#3]
## ❔Question
detect.py文件中第63行中说“如果检测视频的时候想显示出来，可以在这里加一行 view_img = True”
`save_img = True
        # 如果检测视频的时候想显示出来，可以在这里加一行 view_img = True
        view_img = True
        dataset = LoadImages(source, img_size=imgsz)`
我希望在检测时能够将结果实时显示出来，但是貌似加了这一行也并没有什么作用？

如果想要实时输出画框后的结果应该要如何实现呢？

**Comment by FUZhanhong** [comment]
跑detect的时候报错， 
def infer_fast(net, img, net_input_height_size, stride, upsample_ratio, cpu,
               pad_value=(0, 0, 0), img_mean=(128, 128, 128), img_scale=1/256):
    height, width, _ = img.shape   # 实际高宽
请问有遇到吗？怎么解决的？

**Comment by xuyuan-7** [comment]
你好，请问呢你最后解决了吗？

> ## ❔Question
> detect.py文件中第63行中说“如果检测视频的时候想显示出来，可以在这里加一行 view_img = True” `save_img = True # 如果检测视频的时候想显示出来，可以在这里加一行 view_img = True view_img = True dataset = LoadImages(source, img_size=imgsz)` 我希望在检测时能够将结果实时显示出来，但是貌似加了这一行也并没有什么作用？
> 
> 如果想要实时输出画框后的结果应该要如何实现呢？
